# Generated by Django 4.1.7 on 2023-05-20 06:35

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TDSMonitoring",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "tds_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=65, null=True
                    ),
                ),
                (
                    "temperature_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=65, null=True
                    ),
                ),
                ("sensor", models.CharField(blank=True, max_length=65, null=True)),
            ],
            options={
                "verbose_name": "TDS",
                "verbose_name_plural": "TDS",
            },
        ),
    ]
